### ISSUE TITLE
Blood Blade Handle cannot be create.After version update，gears cannot be made，Fluid Encapsulator cannot be made.Whether the products of Stoneling  need to be modified.

### ISSUE THREAD

**Issue by Tyumen666** [Kikiisyourfriend/ProjectIsothermalExpert#3] opened 2022-04-15 05:43 UTC
Blood Blade Handle cannot be create.After version update，gears cannot be made，Fluid Encapsulator cannot be made.Whether the products of Stoneling  need to be modified.

**Comment by itsjusttriz** [comment] 2022-04-15 10:05
Thankyou for reporting this issue. This will be investigated as soon as possible.

**Comment by itsjusttriz** [comment] 2022-04-15 12:24
The Blood Blade handle seems to be craftable as of version 0.3.1 (*Unless there's something I am not noticing?*)

The Fluid Encapsulator & Gears also seem craftable as of version 0.3.1

I'm not sure I understand your issue with the Stoneling? The Spawn egg for this mob is craftable as of 0.3.1
@Tyumen666

**Comment by Kikiisyourfriend** [comment] 2022-04-15 12:24
This is confirmed and mostly fixed. I think there still might be an issue with the handle from a crafted sentient sword.
Will investigate later today on stream.

**Comment by Kikiisyourfriend** [comment] 2022-04-15 12:30
> The Blood Blade handle seems to be craftable as of version 0.3.1 (*Unless there's something I am not noticing?*)
> 
> 
> 
> The Fluid Encapsulator & Gears also seem craftable as of version 0.3.1
> 
> 
> 
> I'm not sure I understand your issue with the Stoneling? The Spawn egg for this mob is craftable as of 0.3.1
> 
> @Tyumen666 

The stoneling issue was it having an entire different pool in mob cages which is now fixed.
Gears were jacked up because the multiservo press used its own gears so that was a wall.
I can't remember what I did with the fluid encapsulator but I need to double check that.
And the sword handle issue might be from a freshly crafted sentient sword rather than just pulling out from JEI.
Will investigate further.

**Comment by itsjusttriz** [comment] 2022-04-15 12:34
@Kikiisyourfriend Ah yea i just tested the Actual sword craft and it doesnt seem to be consuming any blood or anything.

Also the gears seem fine to me? The Multiservo press took diamond gears which according to jei was 
```json
{
    "recipeForExample": [
        [O, X, O],
        [X, O, X],
        [O, X, O]
    ]
}
```
With X being a diamond, O being empty.

But yea if theres underlying issues that im not seeing, then by all means :)

**Comment by Kikiisyourfriend** [comment] 2022-04-15 12:40
> @Kikiisyourfriend Ah yea i just tested the Actual sword craft and it doesnt seem to be consuming any blood or anything.
> 
> 
> 
> Also the gears seem fine to me? The Multiservo press took diamond gears which according to jei was 
> 
> ```json
> 
> {
> 
>     "recipeForExample": [
> 
>         [O, X, O],
> 
>         [X, O, X],
> 
>         [O, X, O]
> 
>     ]
> 
> }
> 
> ```
> 
> With X being a diamond, O being empty.
> 
> 
> 
> But yea if theres underlying issues that im not seeing, then by all means :)

You're correct because now it's fixed. It's fixed in 0.3.1.1 and 0.3.1 but this report was made before those updates.

**Comment by itsjusttriz** [comment] 2022-04-15 12:45
@Kikiisyourfriend ah ok

**Comment by Kikiisyourfriend** [comment] 2022-04-15 14:21
Blood Blade Handle does get crafted. Make sure to use a T2 Blood Altar.

**Comment by Kikiisyourfriend** [comment] 2022-04-15 14:25
Wait. I think I know the problem.

**Comment by Kikiisyourfriend** [comment] 2022-04-15 14:55
Fixed and will be applied with the next update.

**Closed as completed by Kikiisyourfriend** 2022-04-15 14:55 UTC
Labels: Fixed for next update.
