### ISSUE TITLE
[BUG] - *TITLE_HERE*

### ISSUE THREAD

**Issue by MrSoulOfHell** [Kikiisyourfriend/ProjectIsothermalExpert#55] opened 2022-10-09 19:45 UTC
### **Confirm your current modpack version:**

```
1.0
1.0.1
1.0.2 (latest)
1.0.8
```
### **Are you on a server? Or in Singleplayer?:**

```
Singleplayer
```

### **Description:**

```
the autocrafing whit stick
```

### **Steps to reproduce:**

```
 The auto crafting whit crafter any tier and refinded autocrafting whitch involve stick or dirty stick dont work
```
### **Crash log (*if any*):**
> *Must use a code-pasting website such as Pastebin, or a Gist.*

```
HERE
```

**Comment by itsjusttriz** [comment] 2022-10-10 13:06
Duplicate of #53

**Closed as completed by itsjusttriz** 2022-10-10 13:06 UTC
Labels: duplicate
